### PR TITLE
Filter by app names

### PR DESCRIPTION
**Pull request by caetano-dev**
This pull request adds a feature that lets the user choose a given app to search by adding a `!<name>` prefix.

### CODE REVIEW

**Review by jasonjmcghee — COMMENTED** [review]
What if the app name has a space like "App Store"- can you do `!"App Store"`?

**Comment by caetano-dev** [comment]
Damn, I had not thought about that!
It will search only for the first word after the `!`

Maybe letting the user search for `!app-store` or !"App Store" could be a fix?

Capture d’écran 2024-01-02 à 21 27 06

**Comment by jasonjmcghee** [comment]
I bet !"two words" is fine for now, but ideally we'd have a separate sql table of unique application names that we could retrieve from and have a dropdown filter

**Comment by caetano-dev** [comment]
I added a dropdown filter next to the search bar and reverted the changes to search with `!`. 

The apps shown in the menu are updated according to the user's data, meaning that if the user opens a new app, it will be added to the menu, and if the user deletes all their data, the menu will only show "All apps".

https://github.com/jasonjmcghee/rem/assets/55260356/9fc82a0d-a5fa-4fda-8e53-16cba9e82a23

**Review by jasonjmcghee — APPROVED** [review]
I'll approve as this is great and immediately useful, but I would use the suggested approach of a table for unique application names. The current approach needs to do a full scan and that will get slower and slower as users record more and more

**Comment by jasonjmcghee** [comment]
On second pass, when does getAppFilterData get called? Only on initial creation? If I close search and use a new app and reopen it, will it show up?

**Comment by caetano-dev** [comment]
Yes. If you close search, open a new app and search for it again, it will show up.

I am working on the new database table for unique app names. I am testing it and will push the code soon. I hope it addresses the possible performance issues.

**Comment by jasonjmcghee** [comment]
Awesome - happy to merge this as is, and you can open a second pr!

**Comment by caetano-dev** [comment]
Before you merge: I noticed that after stopping the first screen recording and starting a new one, the new frames only show up after searching for something. Do you know if this is something that was happening before?

**Comment by jasonjmcghee** [comment]
@caetano-dev want me to merge this first, then #62 ? Both are looking good!

**Comment by caetano-dev** [comment]
Sure, you can do that!

**Comment by caetano-dev** [comment]
Please, also try to test the changes in your machine before merging with the main branch.

It is working for me, but the more people test it, the better.

**Comment by jasonjmcghee** [comment]
Couple of small tweaks to make proper spacing for the search, and added a border for better visibility:

image

**Pull request merged**
