### PR TITLE
feat:Only OCR active app window

### PR DESCRIPTION
**Pull request by seletz**
This PR implements feature #38.  This feature is only active if the new setting:

image

## Implementation Details

It turns out to be surprisingly difficult to get the bounds of the active window.  After much trying and googling around, I finally adopted code from [SO](https://stackoverflow.com/questions/72763902/swift-get-a-list-of-opened-app-windows-with-desktop-number-and-position-info).  I added `WindowHelper` to hide that code.

The signature of `performOCR` now takes a `NSImage` instead of a `CGImage`.  The `processScreenshot` now passes a cropped `NSImage` based on the bounds of the active window.  Cropping is done in `ImageUtils`.

### CODE REVIEW

**Review by jasonjmcghee — COMMENTED** [review]
This is looking good - out of curiosity, could we do something like this instead?

```swift
guard let display = shareableContent.displays.first else { return }
let activeApplicationName = NSWorkspace.shared.frontmostApplication?.localizedName

let window = shareableContent.windows.first {
    $0.owningApplication?.processID == NSWorkspace.shared.frontmostApplication?.processIdentifier
}
let frame = window?.frame

// ...

guard let image = CGDisplayCreateImage(display.displayID, rect: display.frame) else { return }

if let region = frame {
    let cropped = image.cropping(to: region)
    // OCR
} else {
    // OCR
}
```

**Comment by seletz** [comment]
BTW -- I also added changes to the `project.pbxproj` file -- I hope this is OK.  I have additional changes locally here, mostly related to code signing.

**Comment by seletz** [comment]
@jasonjmcghee Hmm -- will have a look, I believe I tried that and it didn't work.  I'll try again.

**Comment by seletz** [comment]
@jasonjmcghee OK so I removed the ImageHelper as per your suggestion.  However, it seems the window frame returned by the method you suggested does not work properly.  It *does* return a frame, but using this to crop the window renders the OCR output incomplete -- when using the `WindowHelper` this is not the case.  Perhaps I am missing something?

**Comment by jasonjmcghee** [comment]
> @jasonjmcghee Hmm -- will have a look, I believe I tried that and it didn't work. I'll try again.

fwiw - seems to work (tried it real quick)

```swift
let activePid = NSWorkspace.shared.frontmostApplication?.processIdentifier
let window = shareableContent.windows.first { $0.owningApplication?.processID == activePid }
let frame = window?.frame

logger.debug("Active Frame: \(frame?.debugDescription ?? "<undefined>")")
logger.debug("Active Application: \(activeApplicationName ?? "<undefined>")")
```

image

**Comment by jasonjmcghee** [comment]
> @jasonjmcghee OK so I removed the ImageHelper as per your suggestion. However, it seems the window frame returned by the method you suggested does not work properly. It _does_ return a frame, but using this to crop the window renders the OCR output incomplete -- when using the `WindowHelper` this is not the case. Perhaps I am missing something?

😅 the one thing i didn't try - lemme see, maybe it's a pixel scaling issue?

**Comment by jasonjmcghee** [comment]
hm... seems to work for me somehow:

```swift
    ...
    await processScreenshot(frameId: frameId, image: image, frame: window?.frame ?? display.frame)
    ....
```

later

```swift
performOCR(...) {
    ...
    let img = image.cropping(to: frame) ?? image
    self.logger.debug("Active Frame: \(frame.debugDescription)")

    let configuration = ImageAnalyzer.Configuration([.text])
    let nsImage = NSImage(cgImage: img, size: NSSize(width: img.width, height: img.height))
    ...
```

image

**Comment by jasonjmcghee** [comment]
to be clear, likely better to pass the frame as `CGRect?` and only crop if it's present - and then we could only even instantiate the window if the setting exists.

**Comment by jasonjmcghee** [comment]
> but using this to crop the window renders the OCR output incomplete

Maybe I'm not understanding...

Also, i hope it goes without saying I _really_ appreciate you joining as a contributer. it's awesome.

I just want to make sure that if we can manage to do this in like 5 lines of code, we do - also this is using the `ScreenCaptureKit` API which we'll need to use for filtering anyway

**Comment by seletz** [comment]
> Also, i hope it goes without saying I _really_ appreciate you joining as a contributer. it's awesome.
> 
> I just want to make sure that if we can manage to do this in like 5 lines of code, we do - also this is using the `ScreenCaptureKit` API which we'll need to use for filtering anyway

Hah -- no worries.  I've been doing SW development since a very long time.  I'm also old enough.  I really would also like to have a simple solution.  The `WindowHelper` code seems awkward and surprisingly complex.  I'm a Swift and UIKit NOOB, I used to do a little ObjectiveC when iOS was new and hot.  So all in all I contribute (a) because I like the idea of the `rem` app, and (b) I take it as a opportunity to learn something new.

**Comment by seletz** [comment]
> Maybe I'm not understanding...

Well.  When I use the frame of the window found using the ScreenCapture Framework, I found that the OCR result does not contain what I expect.  I tested this by having a terminal window open and active with some text in it.  I was unable to find the text using the `Search` function. 
When I use the frame from `WindowHelper` instead, the text is found.

I did the same test with an open Xcode window -- it does find *some* text, but not all.  I believe the cropped image is not wide enough somehow -- but I need more testing.  I'll test this again later tomorrow.

**Comment by jasonjmcghee** [comment]
Happy to merge as-is if we remove `ImageUtils` which I think is not being used. We can always iterate to find a more `ScreenCaptureKit` approach!

**Comment by jasonjmcghee** [comment]
If you give me permission, happy to co-author by removing ImageUtils and merging your current code @seletz. It's such a great feature and I don't want to halt progress!

**Comment by seletz** [comment]
> If you give me permission, happy to co-author by removing ImageUtils and merging your current code @seletz. It's such a great feature and I don't want to halt progress!

Sure!  Sorry for not reacting, RL keeps interfering :)

**Comment by jasonjmcghee** [comment]
@seletz all good! Is ImageUtils being used? (Is it needed?)

**Comment by seletz** [comment]
FWIW, updated this branch to the latest mainline.  I believe that the cropping is wrong:



So what I said above is wrong., i.e. your window finding method is not the culprit, the cropping is.  I believe that the frame of the window found might use some different units or a different coordinate system.  I'll need to read apple docs to get to the issue.

We might also save the cropped image to disc in some readable format so we can confirm this visually.

**Comment by jasonjmcghee** [comment]
ImageHelper (removed in this PR) has a function to save images. It's for  debugging and shouldn't be deleted imo.

https://github.com/jasonjmcghee/rem/blob/3431d2a7acddf6eeeec19a429001fceafd94853f/rem/ImageHelper.swift#L34

**Comment by seletz** [comment]
> ImageHelper (removed in this PR) has a function to save images. It's for debugging and shouldn't be deleted imo.
> 
> https://github.com/jasonjmcghee/rem/blob/3431d2a7acddf6eeeec19a429001fceafd94853f/rem/ImageHelper.swift#L34

Oh damn, I removed the wrong file -- I'm sorry.  Let me add it again.

**Comment by jasonjmcghee** [comment]
NSScreen has scale factor info fwiw. If that's the issue!

**Comment by seletz** [comment]
So the cropped images look all wrong, verified by your png save function.  I'm now looking at the docs and the frame info.

**Comment by seletz** [comment]
Ah.  CGimage measures in pixels, Window frames in points.  We need to scale.

**Comment by seletz** [comment]
@jasonjmcghee ok this should work now.  Could you please have a look?

**Review by jasonjmcghee — APPROVED** [review]
rem.xcodeproj/project.pbxproj looks out of date, but the code looks awesome and thank you for doing this and getting to this implementation!

**Pull request merged**
