### PR TITLE
Feat:added login item - Rem will run on boot

### PR DESCRIPTION
**Pull request by ruslanjabari**
added https://github.com/sindresorhus/LaunchAtLogin-Modern

note: used the version that works on macOS 13.0+ since the min deployment target for the project is 14.0

### CODE REVIEW

**Comment by jasonjmcghee** [comment]
Thought a lot about this one. I think rem isn't stable enough to warrant this as a feature yet.

Maybe I'm overthinking it?

I remember when I tried out the first version of rewind released, it literally would not close. I'd try closing it, and a few minutes later it would reopen. I genuinely never figured it out until i completely uninstalled it.

I'm concerned about something like that happening if it's not entirely user controlled at this very unstable state.

**Comment by djsavvy** [comment]
For what it's worth, I've set up rem to auto-launch on login by manually adding it to my login items, and I haven't had any issues so far. 

However, it doesn't start auto-remembering this way — I still have to manually toggle "start remembering".

**Comment by Dbz** [comment]
I am also interested in this feature

**Comment by jasonjmcghee** [comment]
Hi @ruslanjabari - I know it's been a few months, but I think things are stable enough that it's the right time to merge this. I integrated your code into our settings manager, and seems to work as it's supposed to in my testing.

I'm going to merge it!

**Comment by ruslanjabari** [comment]
Agreed.

**Pull request merged**
